### ISSUE TITLE
Service not stopping on migration SQL errors

### ISSUE THREAD

**Issue by americ** [micronaut-projects/micronaut-liquibase#13]
Same as #3   - the app starts in spite of Liquibase migration failures.

I stepped through the code and can see the ApplicationContext being told to stop, but once the LiquibaseMigrationRunner completes, the app still reports it started ok (and it continues to run). Maybe a different mechanism is required to do a shutdown during startup?

`
...
16:18:54.233 [main] INFO  l.c.StandardChangeLogHistoryService - Reading from public.databasechangelog
16:18:54.233 [main] INFO  liquibase.executor.jvm.JdbcExecutor - SELECT * FROM public.databasechangelog ORDER BY DATEEXECUTED ASC, ORDEREXECUTED ASC
16:18:54.246 [main] INFO  liquibase.executor.jvm.JdbcExecutor - CREATE TABLE public.badbad (id REALLYBADSQL)
16:18:54.254 [main] ERROR liquibase.changelog.ChangeSet - Change Set classpath:db/changelog/02-bad-bad.xml::01::blah failed.  Error: ERROR: type "reallybadsql" does not exist
  Position: 32 [Failed SQL: CREATE TABLE public.badbad (id REALLYBADSQL)]
16:18:54.258 [main] INFO  l.lockservice.StandardLockService - Successfully released change log lock
16:18:54.260 [main] ERROR i.m.c.d.l.LiquibaseMigrationRunner - Migration failed! Liquibase encountered an exception.
liquibase.exception.MigrationFailedException: Migration failed for change set classpath:db/changelog/02-bad-bad.xml::01::blah:
     Reason: liquibase.exception.DatabaseException: ERROR: type "reallybadsql" does not exist
  Position: 32 [Failed SQL: CREATE TABLE public.badbad (id REALLYBADSQL)]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.performUpdate(LiquibaseMigrationRunner.java:186)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.migrate(LiquibaseMigrationRunner.java:143)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.run(LiquibaseMigrationRunner.java:105)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.lambda$null$0(LiquibaseMigrationRunner.java:87)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.lambda$onCreated$1(LiquibaseMigrationRunner.java:87)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.onCreated(LiquibaseMigrationRunner.java:84)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.onCreated(LiquibaseMigrationRunner.java:60)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1533)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2153)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1751)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1172)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2303)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:199)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at com.blahblah.Application.main(Application.kt:28)
Caused by: liquibase.exception.DatabaseException: ERROR: type "reallybadsql" does not exist
  Position: 32 [Failed SQL: CREATE TABLE public.badbad (id REALLYBADSQL)]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 23 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: type "reallybadsql" does not exist
  Position: 32
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
	... 28 common frames omitted
16:18:54.293 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
16:18:54.307 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
16:18:54.307 [main] WARN  c.zaxxer.hikari.pool.ProxyConnection - HikariPool-1 - Connection org.postgresql.jdbc.PgConnection@fcc6023 marked as broken because of SQLSTATE(08003), ErrorCode(0)
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
	at org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:727)
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:392)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:360)
	at liquibase.database.AbstractJdbcDatabase.close(AbstractJdbcDatabase.java:1154)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.migrate(LiquibaseMigrationRunner.java:156)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.run(LiquibaseMigrationRunner.java:105)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.lambda$null$0(LiquibaseMigrationRunner.java:87)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.lambda$onCreated$1(LiquibaseMigrationRunner.java:87)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.onCreated(LiquibaseMigrationRunner.java:84)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.onCreated(LiquibaseMigrationRunner.java:60)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1533)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2153)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1751)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1172)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2303)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:199)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at com.blahblah.Application.main(Application.kt:28)
16:18:54.307 [main] WARN  l.database.core.PostgresDatabase - Failed to restore the auto commit to true
16:18:54.308 [main] WARN  i.m.c.d.l.LiquibaseMigrationRunner - Error closing the connection after the migration.
liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: This connection has been closed.
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:362)
	at liquibase.database.AbstractJdbcDatabase.close(AbstractJdbcDatabase.java:1154)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.migrate(LiquibaseMigrationRunner.java:156)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.run(LiquibaseMigrationRunner.java:105)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.lambda$null$0(LiquibaseMigrationRunner.java:87)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.lambda$onCreated$1(LiquibaseMigrationRunner.java:87)
	at java.util.Optional.ifPresent(Optional.java:159)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.onCreated(LiquibaseMigrationRunner.java:84)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseMigrationRunner.onCreated(LiquibaseMigrationRunner.java:60)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1533)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2153)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:1751)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1172)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:236)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2303)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:199)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:187)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at com.blahblah.Application.main(Application.kt:28)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
	at org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:727)
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:392)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:360)
	... 19 common frames omitted
16:18:54.981 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 3136ms. Server Running: http://localhost:8080
`

**Comment by jameskleeh** [comment]
@americ Can you upload a sample application?

**Comment by ilopmar** [comment]
Fixed in `1.1.0`
