### ISSUE TITLE
Liquibase periodically fails to start with Micronaut 2.0.0.M2

### ISSUE THREAD

**Issue by JasonTypesCodes** [micronaut-projects/micronaut-liquibase#23]
Please see: https://github.com/JasonTypesCodes/mn2-liquibase-transaction

If you run `./gradlew run`, everything will probably work just fine *most* of the time, but periodically, the application will fail to start stating:
```
> Task :run FAILED
[36m17:40:12.630[0;39m [1;30m[main][0;39m [1;31mERROR[0;39m [35mio.micronaut.runtime.Micronaut[0;39m - Error starting Micronaut server: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [io.micronaut.transaction.jdbc.TransactionalConnection$Intercepted]

Path Taken: new TransactionalConnection$Intercepted(BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors])
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: Error instantiating bean of type  [io.micronaut.transaction.jdbc.TransactionalConnection$Intercepted]

Path Taken: new TransactionalConnection$Intercepted(BeanContext beanContext,Qualifier qualifier,[Interceptor[] interceptors])
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1370)
	at io.micronaut.context.DefaultApplicationContext.initializeContext(DefaultApplicationContext.java:220)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2575)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:211)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:166)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:64)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:294)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:280)
	at mn2.liquibase.transaction.Application.main(Application.java:8)
Caused by: io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.transaction.jdbc.TransactionalConnection$Intercepted]
```

**Comment by graemerocher** [comment]
This is already fixed in micronaut-liquibase 1.3.0. The following resolves the issue

```diff

---
 build.gradle | 10 +++++-----
 1 file changed, 5 insertions(+), 5 deletions(-)

diff --git a/build.gradle b/build.gradle
index 50bc589..0736dae 100644
--- a/build.gradle
+++ b/build.gradle
@@ -20,23 +20,23 @@ configurations {
 }
 
 dependencies {
-    annotationProcessor enforcedPlatform("io.micronaut:micronaut-bom:$micronautVersion")
+    annotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
     annotationProcessor "io.micronaut:micronaut-inject-java"
     annotationProcessor "io.micronaut:micronaut-validation"
-    implementation enforcedPlatform("io.micronaut:micronaut-bom:$micronautVersion")
+    implementation platform("io.micronaut:micronaut-bom:$micronautVersion")
     implementation "io.micronaut:micronaut-inject"
     implementation "io.micronaut:micronaut-validation"
     implementation "io.micronaut:micronaut-runtime"
     implementation "io.micronaut:micronaut-http-server-netty"
     implementation "io.micronaut:micronaut-http-client"
-    implementation("io.micronaut.configuration:micronaut-liquibase")
+    implementation("io.micronaut.configuration:micronaut-liquibase:1.3.0")
     implementation("io.micronaut.data:micronaut-data-hibernate-jpa")
     implementation("io.micronaut.configuration:micronaut-jdbc-tomcat")
     runtimeOnly "ch.qos.logback:logback-classic:1.2.3"
     runtimeOnly "com.h2database:h2"
-    testAnnotationProcessor enforcedPlatform("io.micronaut:micronaut-bom:$micronautVersion")
+    testAnnotationProcessor platform("io.micronaut:micronaut-bom:$micronautVersion")
     testAnnotationProcessor "io.micronaut:micronaut-inject-java"
-    testImplementation enforcedPlatform("io.micronaut:micronaut-bom:$micronautVersion")
+    testImplementation platform("io.micronaut:micronaut-bom:$micronautVersion")
     testImplementation "org.junit.jupiter:junit-jupiter-api"
     testImplementation "io.micronaut.test:micronaut-test-junit5"
     testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine"
-- 
```
