### ISSUE TITLE
org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found

### ISSUE THREAD

**Issue by rlconst** [micronaut-projects/micronaut-liquibase#338]
### Expected Behavior

On 5.7.0 I see following exception.
```
Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method 'void <init>()' not found
	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:24)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:406)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:391)
	at liquibase.Liquibase$16.run(Liquibase.java:2020)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2445)
	at liquibase.Liquibase.listUnrunChangeSets(Liquibase.java:2016)
	at io.micronaut.liquibase.AbstractLiquibaseMigration.isUpdateNeeded(AbstractLiquibaseMigration.java:325)
	at io.micronaut.liquibase.AbstractLiquibaseMigration.performUpdateIfNeeded(AbstractLiquibaseMigration.java:183)
	at io.micronaut.liquibase.AbstractLiquibaseMigration.migrate(AbstractLiquibaseMigration.java:140)
	at io.micronaut.liquibase.AbstractLiquibaseMigration.forceRun(AbstractLiquibaseMigration.java:100)
	at io.micronaut.liquibase.AbstractLiquibaseMigration.run(AbstractLiquibaseMigration.java:86)
	at io.micronaut.liquibase.LiquibaseMigrationRunner.lambda$onCreated$1(LiquibaseMigrationRunner.java:64)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.micronaut.liquibase.LiquibaseMigrationRunner.onCreated(LiquibaseMigrationRunner.java:62)
	at io.micronaut.liquibase.LiquibaseMigrationRunner.onCreated(LiquibaseMigrationRunner.java:39)
	at io.micronaut.context.DefaultBeanContext.triggerBeanCreatedEventListener(DefaultBeanContext.java:2407)
	at io.micronaut.context.DefaultBeanContext.postBeanCreated(DefaultBeanContext.java:2385)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2309)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:2251)
	at io.micronaut.context.DefaultBeanContext.createRegistration(DefaultBeanContext.java:3016)
	at io.micronaut.context.SingletonScope.getOrCreate(SingletonScope.java:80)
	at io.micronaut.context.DefaultBeanContext.findOrCreateSingletonBeanRegistration(DefaultBeanContext.java:2918)
	at io.micronaut.context.DefaultBeanContext.loadContextScopeBean(DefaultBeanContext.java:2737)
	at io.micronaut.context.DefaultBeanContext.initializeContext(DefaultBeanContext.java:1915)
```

Adding `implementation("org.liquibase:liquibase-core:4.20.0")` helps

### Version

3.8.7

**Comment by rlconst** [comment]
I see a PR https://github.com/micronaut-projects/micronaut-liquibase/pull/337 so let's keep this in case someone will search

**Comment by wetted** [comment]
@rlconst Is this still an issue for you? If so, do you have an example project that demonstrates the error?

If I create a Micronaut 3 at [Micronaut Launch](https://micronaut.io/launch), and set the Micronaut version to 3.8.7, dependency resolution upgrades the `org.yaml:snakeyaml:1.33` liquibase-core transitive to v 2.0, which should resolve this problem.

**Comment by rlconst** [comment]
@wetted not relevant anymore
