### ISSUE TITLE
URI is not hierarchical

### ISSUE THREAD

**Issue by stivlo** [micronaut-projects/micronaut-liquibase#4]
I tried to use micronaut-liquibase and I followed the documentation, but the application doesn't start and I get the following error:

```
23:38:03.254 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.configuration.dbmigration.liquibase.$LiquibaseMigrationRunnerDefinition$Intercepted]

Message: URI is not hierarchical
Path Taken: new $LiquibaseMigrationRunnerDefinition$Intercepted(ApplicationContext applicationContext,[ResourceAccessor resourceAccessor],BeanContext beanContext,Interceptor[] interceptors)
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.configuration.dbmigration.liquibase.$LiquibaseMigrationRunnerDefinition$Intercepted]

Message: URI is not hierarchical
Path Taken: new $LiquibaseMigrationRunnerDefinition$Intercepted(ApplicationContext applicationContext,[ResourceAccessor resourceAccessor],BeanContext beanContext,Interceptor[] interceptors)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1492)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2143)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1829)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1809)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:987)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:981)
	at io.micronaut.configuration.dbmigration.liquibase.$$LiquibaseMigrationRunnerDefinition$InterceptedDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1474)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2475)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2397)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:828)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:582)
	at io.micronaut.context.DefaultBeanContext.getBeanRegistrations(DefaultBeanContext.java:349)
	at io.micronaut.context.DefaultBeanContext.initializeEventListeners(DefaultBeanContext.java:1133)
	at io.micronaut.context.DefaultBeanContext.readAllBeanDefinitionClasses(DefaultBeanContext.java:2292)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:199)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:186)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:288)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
	at liquibase.micronaut.test.Application.main(Application.java:8)
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
	at java.base/java.io.File.<init>(File.java:418)
	at liquibase.resource.FileSystemResourceAccessor.addRootPath(FileSystemResourceAccessor.java:51)
	at liquibase.resource.AbstractResourceAccessor.init(AbstractResourceAccessor.java:39)
	at liquibase.resource.FileSystemResourceAccessor.init(FileSystemResourceAccessor.java:44)
	at liquibase.resource.FileSystemResourceAccessor.<init>(FileSystemResourceAccessor.java:26)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseResourceAccessor.buildResourceAccessors(LiquibaseResourceAccessor.java:77)
	at io.micronaut.configuration.dbmigration.liquibase.LiquibaseResourceAccessor.<init>(LiquibaseResourceAccessor.java:45)
	at io.micronaut.configuration.dbmigration.liquibase.$LiquibaseResourceAccessorDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1474)
	... 20 common frames omitted

Process finished with exit code 1
```

I am using openjdk version "11.0.2" 2019-01-15 LTS on a Mac. I created an example project having the issue that I experience:

https://github.com/stivlo/liquibase-micronaut-test

Am I doing anything wrong? Any idea on how to fix? Thank you.

**Comment by ilopmar** [comment]
The issue is because Liquibase was not compatible with Jdk 11. I found this issue https://liquibase.jira.com/browse/CORE-3362 that makes it compatible. Until we release the next `micronaut-liquibase` version with the updated dependency you can define it manually in your `build.gradle`:

```
compile ("org.liquibase:liquibase-core:3.6.3") {
    exclude group: 'org.springframework'
}
```

After this is working, I'm seeing a really strange behavior because the migration is executed 1 minute later after the application starts. I'm digging and comparing with another test application that I have that works properly. I will create a separate issue to track that.

**Comment by scottescue** [comment]
@ilopmar,

> ...I'm seeing a really strange behavior because the migration is executed 1 minute later after the application starts.

Were you able to resolve this, or is there another issue for it? I'm seeing the exact same behavior in my app with OpenJdk 8 (Corretto)

**Comment by ilopmar** [comment]
@scottescue Sorry, I've been busy with other tasks. This is the next thing on my list.

**Comment by ilopmar** [comment]
@scottescue I've found the issue. Do you have defined the packages to scan for JPA entities?

```
jpa:
  default:
    packages-to-scan:
      - 'example.domain'
```

Without at least one class annotated with `@javax.persistence.Entity` in one of the packages defined in `jpa.default.packages-to-scan` property the migrations are not triggered. Please make sure that you have everything configured properly https://micronaut-projects.github.io/micronaut-liquibase/latest/guide/index.html#configuration. If it still doesn't work, please open a new issue with a sample project that reproduces the problem.
