### ISSUE TITLE
NullPointerException when applying migration from a fat jar

### ISSUE THREAD

**Issue by jaksah** [micronaut-projects/micronaut-liquibase#74]
Liquibase 4.0.0 contains some bugfixes for things I've encountered applying liquibase migrations from within a fat jar. There's a comment on [that 3.8.0 is the highest possible version atm](https://github.com/micronaut-projects/micronaut-liquibase/blob/master/gradle.properties#L8-L9), but the issue that the comment [is referring to is now closed](https://github.com/liquibase/liquibase/issues/1051).

When using the [shadow gradle plugin](https://github.com/johnrengelman/shadow) to package a fat jar, the applications fails with `NullPointerException`. The [fix for this is added in liquibase 4.0.0](https://github.com/liquibase/liquibase/commit/ad41dfe1be05a2cbfa565f7b97a76eb7c20ef801#diff-88e17a37cd0501ba274c89af511c6599)

### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [ ] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Expected Behaviour

That liquibase migration can be executed from within a fat jar.

### Actual Behaviour
The migration is executed but the application fails to start with the following exception:
```
	java.lang.NullPointerException: null
		at liquibase.util.LiquibaseUtil.getBuildInfo(LiquibaseUtil.java:45)
		at liquibase.util.LiquibaseUtil.getBuildVersion(LiquibaseUtil.java:17)
		at liquibase.sqlgenerator.core.MarkChangeSetRanGenerator.generateSql(MarkChangeSetRanGenerator.java:91)
		at liquibase.sqlgenerator.core.MarkChangeSetRanGenerator.generateSql(MarkChangeSetRanGenerator.java:25)
		at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
		at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:222)
		at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:25)
		at liquibase.executor.jvm.JdbcExecutor.access$600(JdbcExecutor.java:40)
		at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:384)
		at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:59)
		at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:131)
		at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:111)
		at liquibase.changelog.StandardChangeLogHistoryService.setExecType(StandardChangeLogHistoryService.java:388)
		at liquibase.database.AbstractJdbcDatabase.markChangeSetExecStatus(AbstractJdbcDatabase.java:1130)
		at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:64)
		at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:83)
		at liquibase.Liquibase.update(Liquibase.java:202)
		at liquibase.Liquibase.update(Liquibase.java:179)
		at io.micronaut.liquibase.LiquibaseMigrationRunner.performUpdate(LiquibaseMigrationRunner.java:189)
		at io.micronaut.liquibase.LiquibaseMigrationRunner.migrate(LiquibaseMigrationRunner.java:146)
		at io.micronaut.liquibase.LiquibaseMigrationRunner.run(LiquibaseMigrationRunner.java:109)
		at io.micronaut.liquibase.LiquibaseMigrationRunner.lambda$null$0(LiquibaseMigrationRunner.java:91)
		at java.base/java.util.Optional.ifPresent(Optional.java:183)
		at io.micronaut.liquibase.LiquibaseMigrationRunner.lambda$onCreated$1(LiquibaseMigrationRunner.java:91)
		at java.base/java.util.Optional.ifPresent(Optional.java:183)
		at io.micronaut.liquibase.LiquibaseMigrationRunner.onCreated(LiquibaseMigrationRunner.java:88)
		at io.micronaut.liquibase.LiquibaseMigrationRunner.onCreated(LiquibaseMigrationRunner.java:62)
```

### Environment Information

- **Operating System**: MacOS
- **Micronaut Version:** 2.0.1
- **JDK Version:** Java 11

**Comment by ilopmar** [comment]
This is a major version change and it can't be included in Micronaut 2.0.x. We'll schedule it to be release with Micronaut 2.1.

**Comment by ilopmar** [comment]
The version will be `micronaut-liquibase` `3.0.0`

**Comment by jaksah** [comment]
Alright, thanks. I found a workaround, adding the missing manifest attributes:
```
shadowJar {
    manifest {
        attributes 'Bundle-Version': 'UNKNOWN'
        attributes 'Build-Time': 'UNKNOWN'
    }
}
```

**Comment by jaksah** [comment]
I stumbled upon the [liquibase changelog](https://github.com/liquibase/liquibase/blob/ae6893022ebdd35c0ef20d42aa94a98e380a8bca/changelog.txt#L28) and found out that from the look of it, there's a fix for this with 3.10.1 as well, which looks like the same version where the issue, mentioned in the comment, was fixed. So upgrading to 3.10.1 might be a solution.

**Comment by ilopmar** [comment]
If that's the case, updating the version https://github.com/micronaut-projects/micronaut-liquibase/blob/ea4dec50082ba7da373ed5a18448d975e14f27bf/gradle.properties#L9 and removing https://github.com/micronaut-projects/micronaut-liquibase/blob/dd45515063ff1e50b5b3155b6c9a17f9d3f61d00/liquibase/build.gradle#L33 should be enough.

You can try with version `3.10.0` and run `./gradlew clean check` to make sure that some tests fails. Then upgrade to `3.10.1` and run the tests again. If it works please submit a PR and we can release a new version.

**Comment by jaksah** [comment]
Failed with 3.10.0, worked with 3.10.1 as you suggested. PR created
